[versions]
coroutines = "1.10.2"
kotlin = "2.2.21"
foojay = "1.0.0"
springboot = "3.5.7"
spotless = "8.0.0"
java = "17"
kotlinxSerialization = "1.8.0"
oauth2OidcSdk = "11.30.1"
ktlintVersion = "0.50.0"
bouncyCastle = "1.82"
arrow = "2.2.0"
dependencycheck = "12.1.8"
swaggerUi = "5.30.2"
waltid = "0.11.0"
sdJwt = "0.17.1"
ktor = "3.3.2"
jsonpathkt = "2.0.1"
tink = "1.19.0"
statium = "0.4.0"
kover = "0.9.3"
zxing = "3.5.3"
uri = "0.0.21"
dss = "6.3"
jsonValidator = "2.0.0"
joni = "2.2.6"
aedile = "3.0.1"

[libraries]
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
nimbusds-oauth2-oidc-sdk = { module = "com.nimbusds:oauth2-oidc-sdk", version.ref = "oauth2OidcSdk" }
bouncy-castle = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bouncyCastle" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrow-fx-coroutines = { module = "io.arrow-kt:arrow-fx-coroutines", version.ref = "arrow" }
arrow-core-serialization = { module = "io.arrow-kt:arrow-core-serialization", version.ref = "arrow" }
swagger-ui = { module = "org.webjars:swagger-ui", version.ref = "swaggerUi" }
waltid-mdoc-credentials = { module = "id.walt.mdoc-credentials:waltid-mdoc-credentials-jvm", version.ref = "waltid" }
sd-jwt = { module = "eu.europa.ec.eudi:eudi-lib-jvm-sdjwt-kt", version.ref = "sdJwt" }
ktor-client-apache = { module = "io.ktor:ktor-client-apache", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
jsonpathkt = { module = "com.nfeld.jsonpathkt:jsonpathkt", version.ref = "jsonpathkt" }
tink = { module = "com.google.crypto.tink:tink", version.ref = "tink" }
statium = { module = "eu.europa.ec.eudi:eudi-lib-kmp-statium", version.ref = "statium" }
zxing = { module = "com.google.zxing:javase", version.ref = "zxing" }
uri = { module = "com.eygraber:uri-kmp", version.ref = "uri" }
dss-service = { module = "eu.europa.ec.joinup.sd-dss:dss-service", version.ref = "dss" }
dss-validation = { module = "eu.europa.ec.joinup.sd-dss:dss-validation", version.ref = "dss" }
dss-tsl-validation = { module = "eu.europa.ec.joinup.sd-dss:dss-tsl-validation", version.ref = "dss" }
dss-utils-apache-commons = { module = "eu.europa.ec.joinup.sd-dss:dss-utils-apache-commons", version.ref = "dss" }
json-schema-validator = { module = "com.networknt:json-schema-validator", version.ref = "jsonValidator" }
joni = { module = "org.jruby.joni:joni", version.ref = "joni" }
aedile = { module = "com.sksamuel.aedile:aedile-core", version.ref = "aedile" }

[plugins]
foojay-resolver-convention = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "foojay" }
spring-boot = { id = "org.springframework.boot", version.ref = "springboot" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dependencycheck = { id = "org.owasp.dependencycheck", version.ref = "dependencycheck" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
