[versions]
coroutines = "1.10.1"
kotlin = "2.0.21"
foojay = "0.9.0"
springboot = "3.4.3"
spotless = "7.0.2"
java = "17"
kotlinxSerialization = "1.8.0"
oauth2OidcSdk = "11.23.1"
presentationExchange = "0.3.0"
ktlintVersion = "0.50.0"
bouncyCastle = "1.80"
arrow = "2.0.1"
dependencycheck = "12.1.0"
jacoco = "0.8.11"
swaggerUi = "5.20.1"
waltid = "0.11.0"
sdJwt = "0.12.0"
ktor = "3.1.1"
jsonpathkt = "2.0.1"
tink = "1.17.0"
statium = "0.2.1"
kover = "0.9.1"

[libraries]
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
nimbusds-oauth2-oidc-sdk = { module = "com.nimbusds:oauth2-oidc-sdk", version.ref = "oauth2OidcSdk" }
presentation-exchange = { module = "eu.europa.ec.eudi:eudi-lib-jvm-presentation-exchange-kt", version.ref = "presentationExchange" }
bouncy-castle = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bouncyCastle" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrow-fx-coroutines = { module = "io.arrow-kt:arrow-fx-coroutines", version.ref = "arrow" }
swagger-ui = { module = "org.webjars:swagger-ui", version.ref = "swaggerUi" }
waltid-mdoc-credentials = { module = "id.walt.mdoc-credentials:waltid-mdoc-credentials-jvm", version.ref = "waltid" }
sd-jwt = { module = "eu.europa.ec.eudi:eudi-lib-jvm-sdjwt-kt", version.ref = "sdJwt" }
ktor-client-apache = { module = "io.ktor:ktor-client-apache", version.ref = "ktor" }
jsonpathkt = { module = "com.nfeld.jsonpathkt:jsonpathkt", version.ref = "jsonpathkt" }
tink = { module = "com.google.crypto.tink:tink", version.ref = "tink" }
statium = { module = "eu.europa.ec.eudi:eudi-lib-kmp-statium", version.ref = "statium" }

[plugins]
foojay-resolver-convention = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "foojay" }
spring-boot = { id = "org.springframework.boot", version.ref = "springboot" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dependencycheck = { id = "org.owasp.dependencycheck", version.ref = "dependencycheck" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
